### ISSUE TITLE
SystemJS config filename is hard-coded

### ISSUE THREAD

**Issue by simonwiles** [ngstarter/systemjs-extension#1]
The SystemJS config file in my project is named `systemjs.config.js`, but the filename in this extension is hard-coded to `systemjs.conf.js`; this presents a problem.  Could it be passed in as a configuration variable?

**Comment by antonybudianto** [comment]
sure, I'd make it default to systemjs.conf.js but can be passed as 2nd param, will do it tomorrow.

**Comment by antonybudianto** [comment]
should be fixed in https://github.com/ngstarter/systemjs-extension/commit/156e70922a7517bb1da336666422bb2ac77f2a03

> the config file must still be under `src` folder to work

**Comment by simonwiles** [comment]
that's great, thanks!  is there any reason it needs to be passed separately, rather than simply being a property on the `config.systemJs` object?

**Comment by antonybudianto** [comment]
I think it's more declarative that way, same goes for webpack config

**Comment by simonwiles** [comment]
fair enough -- thanks again!
