### ISSUE TITLE
Missing peer dependency

### ISSUE THREAD

**Issue by jezstarr** [ngstarter/systemjs-extension#2]
In the changes to meet #1 `gulp-util` was added to `index.js` but it is not listed in the `peerDependencies` section in `package.json`. This means that anyone using this extension has to install `gulp-util` separately.

**Comment by antonybudianto** [comment]
but `gulp-util` comes with `gulp`, which is a current peer dependency. Do you use npm v3 ?
It should flatten out dependencies and we can use it

**Comment by jezstarr** [comment]
Oh, I see. We were using npm v2. I've upgraded to npm v3 and it seems to be working now. Thanks for the clarification!

**Comment by antonybudianto** [comment]
Yes, the official angular site recommending npm 3 and node 5
